// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   *string    `gorm:"column:username" json:"username"`
	Password   *string    `gorm:"column:password" json:"password"`
	Email      *string    `gorm:"column:email" json:"email"`
	CreateTime *time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
